ai_challenge/v2023.07.0
AutomotiveAIChallenge/autoware pull request #1
Opened 2023-05-15 08:58 UTC by taikitanaka3

## Description

add gc description

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-05-15 09:28 UTC, s-azumi requested changes

2023-05-15 09:28 UTC, s-azumi commented on autoware.repos
> +    url: git@github.com:tier4/golfcart_description.git
細かいですがURLはHTTPSで統一しておいた方が無難かもです

2023-05-16 00:12 UTC, taikitanaka3 commented on autoware.repos
> +    url: git@github.com:tier4/golfcart_description.git
```suggestion
  # golfcart
  vehicle/golfcart_description:
    url: https://github.com/tier4/golfcart_description.git
    main
```

2023-05-16 01:30 UTC, s-azumi requested changes

2023-05-16 01:30 UTC, s-azumi commented on autoware.repos
> +    version: main
```suggestion
  vehicle/golfcart_description:
    type: git
    url: https://github.com/tier4/golfcart_description.git
    version: main   
```

2023-05-16 01:44 UTC, s-azumi approved these changes

2023-05-16 02:00 UTC, merged